apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: front
spec:
  selector:
    matchLabels:
      app: front
  replicas: 1
  template: 
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: docker.io/tmdwn0704/happy-saving-front:test1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        command: ["/bin/sh", "-c"]
        args:
        - npm run start;
        env:
        - name: REACT_APP_BACK_BASE_URL
          value: http://backend.backend.svc:8000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 2
        resources: {}