apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: front
spec:
  selector:
    app: front
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  # type: ClusterIP
  type: NodePort