apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgres
  name: postgres
spec:
  containers:
  - image: postgres
    name: postgres
    ports:
    - containerPort: 5432
    resources: {}
    env:
    - name: POSTGRES_PASSWORD
      value: 1q2w3e4r
  hostNetwork: true 
status: {}
